name: gmlkit_liveness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
